FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "setuptools<81" opencv-python-headless face_recognition requests qrcode

COPY reconnaissance_camera.py .

ENTRYPOINT ["python3", "reconnaissance_camera.py"]
