-- English descriptions for the 5 shop products
-- Run after seed.sql and seed_shop_descriptions.sql

UPDATE shop_products SET description_en = 'Travel light without sacrificing practicality with this high-resistance polycarbonate cabin suitcase, designed to withstand impacts while remaining remarkably lightweight (2.5 kg). Its four multidirectional 360° wheels glide effortlessly through the busiest airports, and its built-in TSA combination lock spares you any hassle during international security checks. The compartmentalised interior, with retaining straps and a zippered pocket, optimises every cubic centimetre for short trips or as a complement to checked luggage. Compatible with the cabin size standards of major airlines.' WHERE slug='valise-cabine-premium';

UPDATE shop_products SET description_en = 'Designed for demanding trekkers, this 45-litre backpack combines toughness and comfort on the roughest terrain. Its ventilated back panel prevents excessive sweating on long hikes, while the water-repellent fabric effectively protects your belongings from rain and humidity. Side compression straps let you adjust the volume according to your load, and multiple quick-access pockets make it easy to organise your gear. Ideal for a multi-day trek in the Atlas, the Sahara, or any other demanding terrain.' WHERE slug='sac-dos-trek-45l';

UPDATE shop_products SET description_en = 'An essential reference for independent travellers, this 2025 edition Lonely Planet guide covers the whole of Morocco in rich practical and cultural detail. Detailed maps of every region, suggested itineraries, tried-and-tested addresses, budget tips and up-to-date local transport information make it the indispensable companion for planning or accompanying your trip to Morocco — from the imperial medinas to the Sahara desert, via the Atlantic coast resorts.' WHERE slug='guide-maroc-lonely-planet';

UPDATE shop_products SET description_en = 'An authentic piece of Moroccan craftsmanship, this decorative tagine is entirely hand-painted by artisans from the Fez region, the historic cradle of Moroccan ceramics. The traditional geometric patterns, made using techniques passed down through generations, celebrate Morocco''s cultural heritage. More decorative than culinary, this piece finds its place on a shelf, coffee table or sideboard, bringing a touch of authentic Oriental charm to your home. A unique and meaningful travel souvenir.' WHERE slug='tajine-decoratif';

UPDATE shop_products SET description_en = 'An essential for any international traveller, this compact universal adapter is compatible with electrical outlets in over 150 countries worldwide. Equipped with four USB-A ports and one fast-charging USB-C port, it lets you simultaneously charge your smartphone, tablet, camera and laptop without carrying multiple accessories. Its compact format and sturdy casing make it the ideal companion to slip into your carry-on, so you''re never short of battery, wherever you travel.' WHERE slug='adaptateur-universel';
