-- English descriptions for the 28 hotels
-- Run after seed.sql and seed_hotel_descriptions.sql

UPDATE hotels SET description_en = 'La Mamounia has embodied Marrakech''s timeless luxury since 1923. Nestled within eight hectares of century-old gardens planted with olive and orange trees, this legendary palace has welcomed Winston Churchill and some of the world''s most prominent figures. Its refined suites, award-winning spa and Michelin-starred gastronomy regularly place it among the best hotels in the world according to the international press. A stay at La Mamounia is the very essence of Moroccan refinement.' WHERE slug='la-mamounia-marrakech';

UPDATE hotels SET description_en = 'Commissioned by King Mohammed VI, the Royal Mansour redefines luxury with its 53 private riads, each featuring its own pool, terrace and dedicated butler. The architecture, entirely crafted by Moroccan master artisans, celebrates the traditional arts of zellige tilework and tadelakt plaster. Three gourmet restaurants and a 2,600 m² spa complete this address, widely regarded as the ultimate expression of luxury in Marrakech.' WHERE slug='royal-mansour-marrakech';

UPDATE hotels SET description_en = 'Sofitel Casablanca Tour Blanche rises above the city from its upper floors, offering an exceptional panoramic view over the Atlantic Ocean and the Casablanca skyline. Blending contemporary elegance with French-inspired refinement, the hotel features a Sofitel Spa with L''Occitane, several gourmet restaurants and an ideal location close to the business district and the Hassan II Mosque.' WHERE slug='sofitel-casablanca';

UPDATE hotels SET description_en = 'Overlooking the UNESCO-listed medina of Fez, Palais Faraj offers from its panoramic terrace one of the most spectacular views in Morocco, especially at sunset over the city''s thousand rooftops. This restored 19th-century palace combines authentic Moroccan architecture with modern comfort, featuring a traditional spa and refined Fassi cuisine served in salons with original period décor.' WHERE slug='hotel-palais-fes';

UPDATE hotels SET description_en = 'Tucked into the iconic blue alleys of Chefchaouen, Riad Assilah offers an authentic immersion into the unique atmosphere of the Blue Pearl of the Rif. This intimate traditional riad charms guests with its flower-filled courtyard, a terrace overlooking the surrounding mountains, and warm, genuinely Moroccan hospitality, far from the bustle of major tourist cities.' WHERE slug='riad-chefchaouen';

UPDATE hotels SET description_en = 'Owned by Sir Richard Branson and nestled in the foothills of the High Atlas, Kasbah Tamadot offers an exceptional setting between snow-capped mountains and lush Berber valleys. The hotel blends authentic Moroccan craftsmanship with British refinement, featuring traditional Berber suites, luxury tents and a spa with breathtaking views of the Atlas peaks. An ideal stop before or after trekking in the region.' WHERE slug='kasbah-tamadot-atlas';

UPDATE hotels SET description_en = 'Le Méridien Dubai Hotel & Conference Centre combines contemporary elegance with Middle Eastern hospitality in the heart of the Gulf''s most dynamic city. With stunning views over the marina and Dubai''s futuristic skyline, multiple international restaurants and easy access to the city''s iconic malls and attractions, this property is an ideal base for discovering the city of superlatives.' WHERE slug='le-meridien-dubai';

UPDATE hotels SET description_en = 'Four Seasons Resort Bali at Sayan stretches across the heart of the tropical jungle, nestled in a lush valley crossed by the Ayung River, just minutes from the rice terraces of Ubud. Each villa has its own private pool overlooking the canopy. The award-winning spa, Balinese cooking classes and traditional ceremonies offer total immersion in the spirituality and serenity of the Island of the Gods.' WHERE slug='four-seasons-bali';

UPDATE hotels SET description_en = 'Discreet and intimate, Hôtel du Particulier occupies a 19th-century private mansion in the heart of Montmartre, away from Paris''s touristic bustle. Just five suites, each decorated by a different artist, offer a unique, intimate and artistic experience in the capital. Its secret garden and hushed ambiance make it a sought-after, low-key address for travellers seeking authentic Parisian charm.' WHERE slug='hotel-particulier-paris';

UPDATE hotels SET description_en = 'Grand Park Kodhipparu delivers the quintessential Maldivian experience: overwater villas suspended above a crystal-clear turquoise lagoon, with direct access to diving and snorkelling right from your own deck. Each villa features a private pool and stairs leading straight down to the coral reef. Gourmet restaurants, a floating spa and unforgettable sunsets complete this dream stay in the archipelago.' WHERE slug='grand-hotel-maldives';

UPDATE hotels SET description_en = 'Sofitel Agadir Royal Bay Resort stretches along a private beach on Agadir Bay, offering an idyllic seaside setting between the Atlantic Ocean and a palm grove. The property features a traditional hammam, several refined restaurants and direct beach access, ideal for combining seaside relaxation with excursions to the High Atlas and the nearby Ourika Valley.' WHERE slug='sofitel-agadir-royal-bay';

UPDATE hotels SET description_en = 'A member of the prestigious Relais & Châteaux collection, Heure Bleue Palais is built right into the historic ramparts of Essaouira, offering a stunning view over the Atlantic Ocean and the traditional fishing port. Its rooftop pool terrace, marine-inspired spa and gourmet seafood restaurant make it an unmissable charming address in the City of the Winds.' WHERE slug='heure-bleue-palais-essaouira';

UPDATE hotels SET description_en = 'A beautifully restored former royal residence, Fairmont Tazi Palace Tangier overlooks the bay of Tangier from the city''s heights. Seven gourmet restaurants, a modern spa and Andalusian gardens make it a destination in its own right. The hotel blends the architectural heritage of the original palace with contemporary luxury, offering sweeping views of the Strait of Gibraltar and Spain in the distance.' WHERE slug='fairmont-tazi-palace-tanger';

UPDATE hotels SET description_en = 'Sofitel Rabat Jardin des Roses unfolds within peaceful Andalusian gardens just steps from the historic centre of the Moroccan capital. This property blends French elegance with Moroccan refinement in a serene atmosphere away from the bustle, featuring a spa, a rose-surrounded pool and French-Moroccan fusion cuisine served on the terrace.' WHERE slug='sofitel-rabat-jardin-roses';

UPDATE hotels SET description_en = 'A fully restored 19th-century kasbah, Dar Ahlam stands at the edge between the Atlas and the Sahara as a true house of dreams — its name literally means "house of dreams" in Arabic. With no fixed menu and no conventional reception, every stay is fully personalised: surprise dinners in the desert, bespoke excursions and ultra-discreet service make it a confidential address for the most discerning travellers.' WHERE slug='dar-ahlam-ouarzazate';

UPDATE hotels SET description_en = 'Nestled amid the golden dunes of Erg Chebbi in Merzouga, Sahara Stars Camp offers an unrivalled luxury desert camping experience in Morocco. Each private tent has its own en-suite bathroom with hot water, contrasting with the authenticity of the surrounding desert setting. Berber music evenings, stargazing and sunrise over the dunes make this camp a memorable stop on any Saharan tour.' WHERE slug='sahara-stars-camp-merzouga';

UPDATE hotels SET description_en = 'Overlooking the Bosphorus Strait from Istanbul''s European shore, Mandarin Oriental Bosphorus offers suites with panoramic views of Europe''s most iconic waterway. Authentic Ottoman architecture, an award-winning spa inspired by traditional hammams, and refined Turkish gastronomy make this property a benchmark of luxury in Istanbul, between Europe and Asia.' WHERE slug='mandarin-oriental-bosphorus-istanbul';

UPDATE hotels SET description_en = 'A member of The Leading Hotels of the World, Katikies Santorini embodies iconic Cycladic architecture with its white cliffside suites overlooking the volcanic caldera of Santorini. The infinity pool offering breathtaking views of the Aegean Sea and the legendary sunsets of Oia make this address one of the most photographed and sought-after in the Cyclades.' WHERE slug='katikies-santorini';

UPDATE hotels SET description_en = 'Three centuries old, Tawaraya Ryokan perpetuates Japanese hospitality in its most refined form in the heart of Kyoto. Each tatami room, the personalised in-room kaiseki gourmet service, and the traditional baths offer an authentic immersion into ancestral Japanese living, far from mass tourism.' WHERE slug='tawaraya-ryokan-kyoto';

UPDATE hotels SET description_en = 'A former Franciscan monastery whose façade is attributed to Michelangelo, Villa San Michele overlooks Florence and the Arno valley from the hills of Fiesole. This Renaissance residence, part of the Belmond hotel collection, offers a sweeping view of the city of the Medici, terraced gardens and refined Tuscan cuisine in an exceptional historic setting.' WHERE slug='villa-san-michele-florence';

UPDATE hotels SET description_en = 'A century-old symbol of New York luxury, The Plaza Hotel has stood facing Central Park since 1907, having welcomed kings, presidents and celebrities from around the world. Its gilded salons, historic Palm Court for afternoon tea, and sumptuous suites make it a timeless icon of Manhattan, immortalised in countless films and novels.' WHERE slug='the-plaza-new-york';

UPDATE hotels SET description_en = 'Park Hyatt Sydney occupies one of the most coveted locations in Australia, in The Rocks, with every room offering a direct view of the Sydney Opera House or the Harbour Bridge. The rooftop pool, spa and contemporary Australian cuisine complete this address, widely considered the most exclusive in Sydney Harbour.' WHERE slug='park-hyatt-sydney';

UPDATE hotels SET description_en = 'A carefully restored 14th-century monastery, Mandarin Oriental Prague sits in the heart of the historic Malá Strana district, steps from Prague Castle. The hotel has preserved original architectural features, including a baroque chapel transformed into a wellness space, offering a unique experience blending Czech history with contemporary Asian-inspired luxury.' WHERE slug='mandarin-oriental-prague';

UPDATE hotels SET description_en = 'Belmond Hotel Monasterio occupies a beautifully preserved 16th-century monastery in the historic heart of Cusco, former capital of the Inca Empire. Its stone arcades, baroque chapel and silent cloister tell five centuries of Peruvian history. The hotel even offers enriched oxygen in rooms to ease altitude acclimatisation, a unique service suited to its location at 3,400 metres.' WHERE slug='belmond-hotel-monasterio-cuzco';

UPDATE hotels SET description_en = 'An award-winning property, Tulia Zanzibar Unique Beach Resort spreads its romantic bungalows directly facing the Indian Ocean on Zanzibar''s northeast coast. The pristine white sand, turquoise waters and intimate atmosphere make it a favourite destination for honeymoons and couples'' getaways, away from the touristic bustle.' WHERE slug='tulia-zanzibar';

UPDATE hotels SET description_en = 'An Edwardian-style safari lodge evoking the golden age of African exploration, Singita Sasakwa Lodge overlooks the endless Serengeti plain from a privileged hilltop. Each suite offers sweeping views of the savannah crossed by the Great Migration. Expert rangers, sunrise wildlife viewing and refined gastronomy make this address a benchmark of luxury safari in Tanzania.' WHERE slug='singita-sasakwa-lodge-serengeti';

UPDATE hotels SET description_en = 'A historic and iconic address on Copacabana beach since 1923, Copacabana Palace has welcomed generations of stars and heads of state. Its emblematic Art Deco architecture, legendary pool and direct location on Copacabana''s golden sand make it the very symbol of Carioca glamour, in the heart of Rio de Janeiro.' WHERE slug='copacabana-palace-rio';

UPDATE hotels SET description_en = 'Iceland''s capital first resolutely modern luxury hotel, The Reykjavik EDITION combines clean Scandinavian design with warm hospitality on Reykjavik''s waterfront. Its Michelin Guide-recommended restaurant, Nordic spa and proximity to the northern lights viewing sites make it an ideal base for exploring Iceland.' WHERE slug='reykjavik-edition';
