-- English content for the 4 blog posts
-- Run after seed.sql

UPDATE blog_posts SET content_en = '<p>Morocco is home to some of the most authentic and well-preserved medinas in the world. Most are listed as UNESCO World Heritage Sites, standing as living reflections of a thousand-year-old civilisation.</p><h2>1. The medina of Fez</h2><p>The largest medieval medina in the world, with its 9,500 narrow streets, legendary tanneries and ancestral mosques.</p><h2>2. The medina of Marrakech</h2><p>Centred around the mythical Jemaa el-Fna square, a labyrinth of themed souks where every sense is awakened.</p><h2>3. Chefchaouen</h2><p>The blue city of the Rif, where every alley painted in shades of azure is an invitation to photography.</p>' WHERE slug='top-10-medinas-maroc';

UPDATE blog_posts SET content_en = '<p>The Moroccan Sahara is one of the most unforgettable experiences a traveller can have. Here is our complete guide to preparing for your adventure.</p><h2>When to go?</h2><p>The best season is from October to April, when temperatures are mild (20-28°C during the day). Summer is not recommended (40-50°C).</p><h2>How to get there?</h2><p>From Marrakech, expect an 8-9 hour drive via the Tichka Pass and Ouarzazate. Organised tours are the best option.</p>' WHERE slug='guide-sahara-marocain';

UPDATE blog_posts SET content_en = '<p>For any football fan, visiting the Bernabéu and Camp Nou is an absolute dream. Our 7-day programme lets you live this experience in a truly unique way.</p><h2>Day 1-3: Madrid</h2><p>Official tour of the Santiago Bernabéu stadium, the Real Madrid museum, and if possible attendance at a match. Visit to the Prado and tapas in the evening.</p><h2>Day 4-7: Barcelona</h2><p>Camp Nou Experience, the FC Barcelona museum, Barceloneta and Gaudí''s architecture.</p>' WHERE slug='experience-football-espagne';

UPDATE blog_posts SET content_en = '<p>Moroccan cuisine is one of the richest and most complex in the world, the fruit of a blend of Berber, Arab, Andalusian and African cultures.</p><h2>The tagine</h2><p>Slow-cooked in its conical earthenware dish, the tagine develops incomparable aromas.</p><h2>Friday couscous</h2><p>A traditional dish served after Friday prayers, couscous is far more than a meal — it is a family ritual.</p>' WHERE slug='gastronomie-marocaine-secrets';
