-- Descriptions longues pour les 5 produits boutique (remplace les descriptions trop courtes)
-- A executer apres seed.sql

UPDATE shop_products SET description_fr = 'Voyagez léger sans sacrifier la praticité avec cette valise cabine en polycarbonate haute résistance, conçue pour résister aux chocs tout en restant remarquablement légère (2.5 kg). Ses quatre roues multidirectionnelles à 360° glissent sans effort dans les aéroports les plus fréquentés, et sa serrure à combinaison TSA intégrée vous évite tout désagrément lors des contrôles de sécurité internationaux. L''intérieur compartimenté avec sangles de maintien et pochette zippée optimise chaque centimètre cube pour vos voyages courts ou en complément d''un bagage en soute. Compatible avec les normes cabine des principales compagnies aériennes.' WHERE slug='valise-cabine-premium';

UPDATE shop_products SET description_fr = 'Conçu pour les trekkeurs exigeants, ce sac à dos de 45 litres allie robustesse et confort sur les terrains les plus accidentés. Sa structure dorsale ventilée évite la transpiration excessive lors des longues randonnées, tandis que le tissu déperlant protège efficacement vos affaires contre la pluie et l''humidité. Les sangles de compression latérales permettent d''ajuster le volume selon votre chargement, et les multiples poches d''accès rapide facilitent l''organisation de votre matériel. Idéal pour un trek de plusieurs jours dans l''Atlas, le Sahara ou tout autre terrain exigeant.' WHERE slug='sac-dos-trek-45l';

UPDATE shop_products SET description_fr = 'Référence incontournable des voyageurs indépendants, ce guide Lonely Planet édition 2025 couvre l''intégralité du territoire marocain avec un luxe de détails pratiques et culturels. Cartes détaillées de chaque région, itinéraires suggérés, adresses testées et approuvées, conseils budget et informations actualisées sur les transports locaux en font l''outil indispensable pour préparer ou accompagner votre séjour au Maroc, des médinas impériales au désert du Sahara en passant par les stations balnéaires de l''Atlantique.' WHERE slug='guide-maroc-lonely-planet';

UPDATE shop_products SET description_fr = 'Pièce d''artisanat marocain authentique, ce tajine décoratif est entièrement peint à la main par des artisans de la région de Fès, berceau historique de la céramique marocaine. Les motifs géométriques traditionnels, réalisés selon des techniques transmises de génération en génération, célèbrent l''héritage culturel du Maroc. Davantage décoratif que culinaire, cet objet trouve sa place sur une étagère, une table basse ou un buffet pour apporter une touche d''authenticité orientale à votre intérieur. Un souvenir de voyage unique et chargé de sens.' WHERE slug='tajine-decoratif';

UPDATE shop_products SET description_fr = 'Indispensable pour tout voyageur international, cet adaptateur universel compact est compatible avec les prises électriques de plus de 150 pays à travers le monde. Équipé de quatre ports USB-A et d''un port USB-C à charge rapide, il permet de recharger simultanément smartphone, tablette, appareil photo et ordinateur portable sans multiplier les accessoires. Son format compact et son boîtier résistant en font le compagnon idéal à glisser dans votre bagage cabine pour ne jamais être à court de batterie, où que vous voyagiez.' WHERE slug='adaptateur-universel';
