-- Descriptions longues pour les 28 hotels (remplace les taglines trop courtes)
-- A executer apres seed.sql

UPDATE hotels SET description_fr = 'La Mamounia incarne le luxe intemporel de Marrakech depuis 1923. Niché dans des jardins centenaires de huit hectares plantés d''oliviers et d''orangers, ce palais légendaire a accueilli Winston Churchill et les plus grandes personnalités du monde entier. Ses suites raffinées, son spa primé et sa gastronomie étoilée en font régulièrement l''un des meilleurs hôtels du monde selon la presse internationale. Un séjour à La Mamounia, c''est l''essence même du raffinement marocain.' WHERE slug='la-mamounia-marrakech';

UPDATE hotels SET description_fr = 'Conçu sur ordre du Roi Mohammed VI, le Royal Mansour repousse les limites du luxe avec ses 53 riads privés disposant chacun de leur propre piscine, terrasse et majordome dédié. L''architecture, entièrement réalisée par des maîtres artisans marocains, célèbre les arts traditionnels du zellige et du tadelakt. Trois restaurants gastronomiques et un spa de 2600 m² complètent cette adresse considérée comme l''ultime expression du luxe à Marrakech.' WHERE slug='royal-mansour-marrakech';

UPDATE hotels SET description_fr = 'Le Sofitel Casablanca Tour Blanche domine la ville depuis ses étages supérieurs offrant une vue panoramique exceptionnelle sur l''océan Atlantique et la skyline de Casablanca. Alliant élégance contemporaine et raffinement à la française, l''hôtel propose un spa Sofitel Spa with L''Occitane, plusieurs restaurants gastronomiques et un emplacement idéal à proximité du quartier d''affaires et de la Mosquée Hassan II.' WHERE slug='sofitel-casablanca';

UPDATE hotels SET description_fr = 'Surplombant la médina millénaire de Fès classée à l''UNESCO, le Palais Faraj offre depuis sa terrasse panoramique l''une des vues les plus spectaculaires du Maroc, en particulier au coucher du soleil sur les mille toits de la ville. Cet ancien palais du XIXe siècle restauré conjugue authenticité architecturale marocaine et confort moderne, avec un spa traditionnel et une cuisine fassie raffinée servie dans des salons aux décors d''origine.' WHERE slug='hotel-palais-fes';

UPDATE hotels SET description_fr = 'Niché au cœur des ruelles bleues emblématiques de Chefchaouen, le Riad Assilah offre une immersion authentique dans l''atmosphère unique de la perle bleue du Rif. Ce riad traditionnel à taille humaine séduit par son patio fleuri, sa terrasse offrant une vue sur les montagnes environnantes et son accueil chaleureux typiquement marocain, loin de l''agitation des grandes villes touristiques.' WHERE slug='riad-chefchaouen';

UPDATE hotels SET description_fr = 'Propriété de Sir Richard Branson nichée dans les contreforts du Haut Atlas, la Kasbah Tamadot offre un cadre exceptionnel entre montagnes enneigées et vallées berbères verdoyantes. L''hôtel mêle artisanat marocain authentique et raffinement britannique, avec ses suites berbères traditionnelles, ses tentes de luxe et son spa offrant une vue imprenable sur les sommets de l''Atlas. Une étape idéale avant ou après un trek dans la région.' WHERE slug='kasbah-tamadot-atlas';

UPDATE hotels SET description_fr = 'Le Méridien Dubaï Hotel & Conference Centre conjugue élégance contemporaine et hospitalité moyen-orientale au cœur de la ville la plus dynamique du Golfe. Avec sa vue imprenable sur la marina et la skyline futuriste de Dubaï, ses multiples restaurants internationaux et son accès facilité aux centres commerciaux et attractions emblématiques, cet établissement constitue une base idéale pour découvrir la cité des superlatifs.' WHERE slug='le-meridien-dubai';

UPDATE hotels SET description_fr = 'Le Four Seasons Resort Bali at Sayan s''étend au cœur de la jungle tropicale, niché dans une vallée verdoyante traversée par la rivière Ayung, à quelques minutes des rizières en terrasses d''Ubud. Chaque villa dispose de sa propre piscine privée surplombant la canopée. Le spa primé, les cours de cuisine balinaise et les cérémonies traditionnelles offrent une immersion totale dans la spiritualité et la sérénité de l''île des dieux.' WHERE slug='four-seasons-bali';

UPDATE hotels SET description_fr = 'Discret et confidentiel, l''Hôtel du Particulier se love dans un hôtel particulier du XIXe siècle au cœur de Montmartre, loin de l''agitation touristique parisienne. Seulement cinq suites, chacune décorée par un artiste différent, offrent une expérience intimiste et artistique unique dans la capitale. Son jardin secret et son ambiance feutrée en font une adresse confidentielle prisée des voyageurs en quête d''authenticité parisienne.' WHERE slug='hotel-particulier-paris';

UPDATE hotels SET description_fr = 'Le Grand Park Kodhipparu offre l''expérience maldivienne par excellence : des villas sur pilotis suspendues au-dessus d''un lagon turquoise cristallin, avec accès direct à la plongée et au snorkeling depuis votre propre terrasse. Chaque villa dispose d''une piscine privée et d''un escalier menant directement au récif corallien. Restaurants gastronomiques, spa flottant et couchers de soleil inoubliables complètent ce séjour de rêve dans l''archipel.' WHERE slug='grand-hotel-maldives';

UPDATE hotels SET description_fr = 'Le Sofitel Agadir Royal Bay Resort s''étend en bord de plage privée sur la baie d''Agadir, offrant un cadre balnéaire idyllique entre océan Atlantique et palmeraie. L''établissement propose un hammam traditionnel, plusieurs restaurants raffinés et un accès direct à la plage, idéal pour combiner détente balnéaire et excursions vers le Haut Atlas et la vallée de l''Ourika toute proche.' WHERE slug='sofitel-agadir-royal-bay';

UPDATE hotels SET description_fr = 'Membre des prestigieux Relais & Châteaux, l''Heure Bleue Palais est construit à même les remparts historiques d''Essaouira, offrant une vue imprenable sur l''océan Atlantique et le port de pêche traditionnel. Sa terrasse-piscine sur le toit, son spa marin et son restaurant gastronomique de fruits de mer en font une adresse de charme incontournable de la cité des Alizés.' WHERE slug='heure-bleue-palais-essaouira';

UPDATE hotels SET description_fr = 'Ancienne résidence royale magnifiquement restaurée, le Fairmont Tazi Palace Tangier domine la baie de Tanger depuis les hauteurs de la ville. Sept restaurants gastronomiques, un spa moderne et des jardins andalous en font une destination en soi. L''hôtel allie l''héritage architectural du palais d''origine à un luxe contemporain, avec une vue imprenable sur le détroit de Gibraltar et l''Espagne au loin.' WHERE slug='fairmont-tazi-palace-tanger';

UPDATE hotels SET description_fr = 'Le Sofitel Rabat Jardin des Roses se déploie au sein de jardins andalous paisibles à deux pas du centre historique de la capitale marocaine. Cet établissement marie élégance française et raffinement marocain dans une atmosphère sereine, loin de l''agitation, avec son spa, sa piscine entourée de roses et sa cuisine fusion franco-marocaine servie en terrasse.' WHERE slug='sofitel-rabat-jardin-roses';

UPDATE hotels SET description_fr = 'Kasbah du XIXe siècle entièrement rénovée, Dar Ahlam se dresse à la lisière entre l''Atlas et le Sahara comme une véritable maison de rêve, dont le nom signifie littéralement "maison des rêves" en arabe. Sans menu fixe, sans réception classique, chaque séjour est entièrement personnalisé : dîners surprises dans le désert, excursions sur mesure et service ultra-discret en font une adresse confidentielle pour voyageurs exigeants en quête d''exception.' WHERE slug='dar-ahlam-ouarzazate';

UPDATE hotels SET description_fr = 'Niché au cœur des dunes dorées de l''Erg Chebbi à Merzouga, le Sahara Stars Camp offre une expérience de bivouac de luxe inégalée dans le désert marocain. Chaque tente privée dispose de sa propre salle de bain avec eau chaude, contrastant avec l''authenticité du cadre désertique environnant. Soirées musicales berbères, observation des étoiles et lever de soleil sur les dunes font de ce camp une étape mémorable de tout circuit saharien.' WHERE slug='sahara-stars-camp-merzouga';

UPDATE hotels SET description_fr = 'Surplombant le détroit du Bosphore depuis la rive européenne d''Istanbul, le Mandarin Oriental Bosphorus offre des suites avec vue panoramique sur le passage maritime le plus emblématique d''Europe. L''architecture ottomane authentique, le spa primé inspiré des hammams traditionnels et la gastronomie turque raffinée font de cet établissement une référence du luxe stambouliote, entre Europe et Asie.' WHERE slug='mandarin-oriental-bosphorus-istanbul';

UPDATE hotels SET description_fr = 'Membre des Leading Hotels of the World, le Katikies Santorini incarne l''architecture cycladique iconique avec ses suites blanches à flanc de falaise dominant la caldeira volcanique de Santorin. La piscine suspendue offrant une vue à couper le souffle sur la mer Égée et les couchers de soleil légendaires d''Oia font de cette adresse l''une des plus photographiées et recherchées des Cyclades.' WHERE slug='katikies-santorini';

UPDATE hotels SET description_fr = 'Vieux de trois siècles, le Tawaraya Ryokan perpétue la tradition hôtelière japonaise dans sa forme la plus raffinée au cœur de Kyoto. Chaque chambre en tatami, le service personnalisé d''un kaiseki gastronomique servi en chambre et les bains traditionnels offrent une immersion authentique dans l''art de vivre japonais ancestral, loin du tourisme de masse.' WHERE slug='tawaraya-ryokan-kyoto';

UPDATE hotels SET description_fr = 'Ancien monastère franciscain dont la façade serait attribuée à Michel-Ange, la Villa San Michele domine Florence et la vallée de l''Arno depuis les collines de Fiesole. Cette demeure Renaissance, membre des hôtels Belmond, offre une vue imprenable sur la cité des Médicis, des jardins en terrasses et une cuisine toscane raffinée dans un cadre historique d''exception.' WHERE slug='villa-san-michele-florence';

UPDATE hotels SET description_fr = 'Symbole centenaire du luxe new-yorkais, The Plaza Hotel se dresse face à Central Park depuis 1907, ayant accueilli rois, présidents et célébrités du monde entier. Ses salons dorés, son Palm Court historique pour le thé l''après-midi et ses suites somptueuses en font une icône intemporelle de Manhattan, immortalisée par de nombreux films et romans.' WHERE slug='the-plaza-new-york';

UPDATE hotels SET description_fr = 'Le Park Hyatt Sydney occupe l''un des emplacements les plus prisés d''Australie, à The Rocks, avec chaque chambre offrant une vue directe sur l''Opéra de Sydney ou le Harbour Bridge. La piscine sur le toit, le spa et la gastronomie australienne contemporaine complètent cette adresse considérée comme la plus exclusive de la baie de Sydney.' WHERE slug='park-hyatt-sydney';

UPDATE hotels SET description_fr = 'Ancien monastère du XIVe siècle restauré avec soin, le Mandarin Oriental Prague se love au cœur du quartier historique de Mala Strana, à deux pas du Château de Prague. L''hôtel a préservé des éléments architecturaux d''origine, dont une chapelle baroque transformée en espace bien-être, offrant une expérience unique entre histoire tchèque et luxe contemporain asiatique.' WHERE slug='mandarin-oriental-prague';

UPDATE hotels SET description_fr = 'Le Belmond Hotel Monasterio occupe un monastère du XVIe siècle magnifiquement préservé au cœur historique de Cusco, ancienne capitale de l''empire inca. Ses arcades de pierre, sa chapelle baroque et son cloître silencieux racontent cinq siècles d''histoire péruvienne. L''hôtel propose même de l''oxygène enrichi en chambre pour faciliter l''acclimatation à l''altitude, un service unique adapté à son emplacement à 3400 mètres.' WHERE slug='belmond-hotel-monasterio-cuzco';

UPDATE hotels SET description_fr = 'Récompensé à plusieurs reprises, Tulia Zanzibar Unique Beach Resort déploie ses bungalows romantiques directement face à l''océan Indien sur la côte nord-est de Zanzibar. Le sable blanc immaculé, les eaux turquoise et l''atmosphère intimiste en font une destination de prédilection pour les lunes de miel et séjours en couple, à l''écart de l''agitation touristique.' WHERE slug='tulia-zanzibar';

UPDATE hotels SET description_fr = 'Lodge de safari au style édouardien évoquant l''âge d''or des explorations africaines, le Singita Sasakwa Lodge surplombe la plaine infinie du Serengeti depuis une colline privilégiée. Chaque suite offre une vue imprenable sur la savane où transite la Grande Migration. Rangers experts, observation de la faune au lever du soleil et gastronomie raffinée font de cette adresse une référence du safari de luxe en Tanzanie.' WHERE slug='singita-sasakwa-lodge-serengeti';

UPDATE hotels SET description_fr = 'Adresse historique et incontournable de la plage de Copacabana depuis 1923, le Copacabana Palace a accueilli des générations de stars et de chefs d''État. Son architecture Art déco emblématique, sa piscine légendaire et son emplacement direct sur le sable doré de Copacabana en font le symbole même du glamour carioca, au cœur de Rio de Janeiro.' WHERE slug='copacabana-palace-rio';

UPDATE hotels SET description_fr = 'Premier hôtel de luxe résolument moderne de la capitale islandaise, The Reykjavik EDITION conjugue design scandinave épuré et hospitalité chaleureuse au cœur du front de mer de Reykjavik. Son restaurant gastronomique recommandé par le Guide Michelin, son spa nordique et sa proximité avec les sites d''observation des aurores boréales en font une base idéale pour explorer l''Islande.' WHERE slug='reykjavik-edition';
