"""sync destinations columns model and schema

Revision ID: 1b415bbf4575
Revises: 
Create Date: 2026-06-16 23:10:12.025667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b415bbf4575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_low', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('budget_high', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency_local', sa.String(length=30), nullable=True))

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('currency_local')
        batch_op.drop_column('budget_high')
        batch_op.drop_column('budget_low')

    # ### end Alembic commands ###
